services:
  image-classifier:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/home/appuser/.cache/huggingface
    volumes:
      # Optional: Mount a cache directory for Hugging Face models
      - huggingface_cache:/home/appuser/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  huggingface_cache:
